// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_pthoma24.Models;

namespace Mission6_pthoma24.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230210000208_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_pthoma24.Models.MovieEntry", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short?>("Year")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Fantasy/Adventure",
                            Director = "Peter Jackson",
                            Edited = false,
                            Lent_to = "",
                            Notes = "10/10",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            Year = (short)2001
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Fantasy/Adventure",
                            Director = "Peter Jackson",
                            Edited = false,
                            Lent_to = "",
                            Notes = "10/10",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Two Towers",
                            Year = (short)2002
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Fantasy/Adventure",
                            Director = "Peter Jackson",
                            Edited = false,
                            Lent_to = "",
                            Notes = "10/10",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Return of the King",
                            Year = (short)2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
