// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_pthoma24.Models;

namespace Mission6_pthoma24.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_pthoma24.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fantasy/Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("Mission6_pthoma24.Models.MovieEntry", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short?>("Year")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Director = "Peter Jackson",
                            Edited = false,
                            Lent_to = "",
                            Notes = "10/10",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            Year = (short)2001
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1,
                            Director = "Peter Jackson",
                            Edited = false,
                            Lent_to = "",
                            Notes = "10/10",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Two Towers",
                            Year = (short)2002
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 1,
                            Director = "Peter Jackson",
                            Edited = false,
                            Lent_to = "",
                            Notes = "10/10",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Return of the King",
                            Year = (short)2003
                        });
                });

            modelBuilder.Entity("Mission6_pthoma24.Models.MovieEntry", b =>
                {
                    b.HasOne("Mission6_pthoma24.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
